{
 "title": "Process history",
 "time": { "from": "2020-07-31T09:51:33.904Z", "to": "2020-07-31T10:06:31.905Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM node ORDER BY node ASC;"
   },
   { "name": "regname", "label": "Registered name" },
   { "name": "pid" }
  ]
 },
 "panels": [
  {
   "title": "Reductions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  dreductions\nFROM\n  prc\nWHERE\n  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]' AND\n    ( ('[[pid]]'     != '' AND pid='[[pid]]') OR                  -- pid is set\n      ('[[regname]]' != '' AND registered_name='[[regname]]') OR  -- registered_name is set\n      ('[[pid]]'     =  '' AND '[[regname]]' = '')                -- none is set, show all processes\n    )\nORDER BY ts\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  stack_size, heap_size, total_heap_size, memory\nFROM\n  prc\nWHERE\n (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]' AND\n    ( ('[[pid]]'     != '' AND pid='[[pid]]') OR                  -- pid is set\n      ('[[regname]]' != '' AND registered_name='[[regname]]') OR  -- registered_name is set\n      ('[[pid]]'     =  '' AND '[[regname]]' = '')                -- none is set, show all processes\n    ) \nORDER BY ts\n"
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts), message_queue_len\nFROM prc\nWHERE\n  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]' AND\n    ( ('[[pid]]'     != '' AND pid='[[pid]]') OR                  -- pid is set\n      ('[[regname]]' != '' AND registered_name='[[regname]]') OR  -- registered_name is set\n      ('[[pid]]'     =  '' AND '[[regname]]' = '')                -- none is set, show all processes\n    )\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Current function",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT ts, registered_name, pid, current_function FROM prc \nWHERE \n  (ts BETWEEN $__timeFrom() AND $__timeTo()) AND \n  node='[[node]]' AND\n    ( ('[[pid]]'     != '' AND pid='[[pid]]') OR                  -- pid is set\n      ('[[regname]]' != '' AND registered_name='[[regname]]') OR  -- registered_name is set\n      ('[[pid]]'     =  '' AND '[[regname]]' = '')                -- none is set, show all processes\n    )\n"
    }
   ]
  }
 ]
}